@version: 3.38

options {
    chain_hostnames(no);
    flush_lines(1);
    use_dns(no);
    use_fqdn(no);
    keep_hostname(yes);
    stats_freq(0);
};

source s_local {
    internal();
    unix-dgram("/dev/log");
};

filter f_slapd {
    facility(local4);
};

destination d_slapd {
    file("/var/log/slapd/slapd.log" create_dirs(yes));
};

destination d_messages {
    file("/var/log/slapd/messages.log" create_dirs(yes));
};

log {
    source(s_local);
    filter(f_slapd);
    destination(d_slapd);
};

log {
    source(s_local);
    destination(d_messages);
};

